### ISSUE TITLE
IDE learn command error

### ISSUE THREAD

**Issue by dwinniford** [learn-co-curriculum/programming-univbasics-4-intro-to-hashes-lab#5]
![Error2](https://user-images.githubusercontent.com/58039580/70676053-8c001b00-1c50-11ea-9eb6-c11ba8e7984b.JPG)

**Comment by maxwellbenton** [comment]
Hi @dwinniford, 

Thank you for providing this feedback. This error is common when dealing with hashes, and is most likely due to a missing curly brace indicating the end of a hash. We've updated this lesson with an additional message on this error, what may be the cause, and how to potentially avoid it, which should help prevent this for future students, which should resolve this issue in the future.

Thank you for taking the time to contribute to a Learn lesson!
