### ISSUE TITLE
Error Outside of the Example

### ISSUE THREAD

**Issue by cody-demartin** [learn-co-curriculum/programming-univbasics-4-intro-to-hashes-lab#6]
Hi when running learn submit I receive the following error message: `An error occurred while loading ./spec/intro_to_ruby_hashes_lab_spec.rb.
Failure/Error: require_relative '../intro_to_ruby_hashes_lab.rb'

SyntaxError:
  /home/cdemarti/programming-univbasics-4-intro-to-hashes-lab-nyc01-seng-ft-042020/intro_to_ruby_hashes_lab.rb:36: syntax error, unexpected end-of-input, expecting end
# ./spec/intro_to_ruby_hashes_lab_spec.rb:2:in `require_relative'
# ./spec/intro_to_ruby_hashes_lab_spec.rb:2:in `<top (required)>'
No examples found.

Finished in 0.00023 seconds (files took 0.25789 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

[20:58:54] (master) programming-univbasics-4-intro-to-hashes-lab-nyc01-seng-ft-0`

**Comment by maxwellbenton** [comment]
Hi @cdemarti,

Thank you for providing this feedback. This error is common when dealing with hashes, and is most likely due to a missing curly brace indicating the end of a hash. We've updated this lesson with an additional message on this error, what may be the cause and how to potentially avoid it, which should help prevent this for future students, which should resolve this issue in the future.

Thank you for taking the time to contribute to a Learn lesson!
